
title: My Resume
url: 'http://sawitri.github.io'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: sawitri  ## put your name
title: 'sawitri &amp;' ## your title
location: Ubon Ratchtanai 


## Social Profiles
facebook: http://www.facebook.com  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: http://www.linkedin.com  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
